# nvfetcher.toml
[manix]
src.git      = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"


[starship]
# src.git    ="https://github.com/starship/starship"
src.manual           = "v1.9.1"
fetch.github         = "starship/starship"
cargo_lock           = "Cargo.lock"
[starship.passthru]
rustToolchainChannel = "nightly"
rustToolchainDate    = "2022-07-01"
rustToolchainSha256  = "sha256-HhkjtODLw16O7DNPew9+vqOtbM6hcAmLH55XnZ0G6Fk="
# rustToolchainSha256  = "0000000000000000000000000000000000000000000000000000000000000000"
### TODO generate entry with auto-sha

[revealjs]
src.manual           = "4.1.2"
fetch.github         = "hakimel/reveal.js"
