# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/163e8552-861a-4208-bc26-b21c7530efd2";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/850D-642E";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f327c6ed-a063-4f61-890d-9db987ab9770";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/aa8f902a-50cc-45cc-9aeb-ccad00da902d";
      fsType = "btrfs";
      options = [ "subvol=docker" ];
    };

  fileSystems."/home/nvme" =
    { device = "/dev/disk/by-uuid/aa8f902a-50cc-45cc-9aeb-ccad00da902d";
      fsType = "btrfs";
      options = [ "subvol=nvme" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/aa8f902a-50cc-45cc-9aeb-ccad00da902d";
      fsType = "btrfs";
      options = [ "subvol=tmp" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/895ffa0b-c332-4350-9a6d-2e6ebf552f26"; }
    ];

}
