# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8eeb7fe3-5c11-4fa5-98e7-7dc9cbbea063";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/258a4c52-19a3-4e53-9a2a-99a071ae45db";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F8F4-3E6E";
      fsType = "vfat";
    };

  # fileSystems."/var/lib/docker/btrfs" =
  #   { device = "/var/lib/docker/btrfs";
  #     fsType = "none";
  #     options = [ "bind" ];
  #   };

  # fileSystems."/var/lib/kubelet/pods/b6ebd5d9-f694-48d8-a561-31a8dfccdc7b/volumes/kubernetes.io~projected/kube-api-access-966kj" =
  #   { device = "tmpfs";
  #     fsType = "tmpfs";
  #   };

  # fileSystems."/var/lib/kubelet/pods/92b805a9-4e90-4097-9bbf-627fe016e68d/volumes/kubernetes.io~projected/kube-api-access-sfxv5" =
  #   { device = "tmpfs";
  #     fsType = "tmpfs";
  #   };

  # fileSystems."/var/lib/kubelet/pods/1c359ed4-dd41-48bb-bc01-16d5b633adaa/volumes/kubernetes.io~projected/kube-api-access-r9vk5" =
  #   { device = "tmpfs";
  #     fsType = "tmpfs";
  #   };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e073c3cc-11c4-42e0-90d4-2115929c958e"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
