#!/usr/bin/env zsh
###
### ---
### name:
###   summonPulumi
### abstract:
###   "summonPulumi: augment call to Pulumi with secrets"
### usage: |
###   via aliases
###
### info: |
###    `pulumi --help`
###    `summon --help`
###
### ---
###
function summonPulumi() {
  ENV=${1}
  PULUMI_ARGS=${@:2}
  summon                                                                   \
    --provider /etc/profiles/per-user/${USER}/bin/gopass-summon-provider   \
    --up                                                                   \
    --environment ${ENV}                                                   \
    zsh -c "pulumi ${PULUMI_ARGS}"
}

summonPulumi "${@}"
