#!/usr/bin/env zsh
###
### ---
### name:
###   templateTestDotLocal
### abstract:
###   "FullNameWithUppercaseLettersFoundInTheAbbreviation: description"
### usage: |
###   templateTestDotLocal [ARGS]
###
### info: |
###    misc - URLs, references, man-pages
###
###
### ---
###
function templateTestDotLocal() {
}
templateTestDotLocal ${@};
