# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  cert-manager = {
    pname = "cert-manager";
    version = "v1.9.1";
    src = fetchurl {
      url = "https://github.com/jetstack/cert-manager/releases/download/v1.9.1/kubectl-cert_manager-linux-amd64.tar.gz";
      sha256 = "sha256-6ttScrr2EoziHvfIQjNWt423hZDtqOCI6dq0+NkHxkk=";
    };
  };
  crd2pulumi = {
    pname = "crd2pulumi";
    version = "v1.2.0";
    src = fetchFromGitHub ({
      owner = "pulumi";
      repo = "crd2pulumi";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-jGCtHDceJMGG2WHRldEyToZRNp3ZTt4Tir7DAsaWgfI=";
    });
    vendorSha256 = "sha256-XM1uedApVLkFzUpNPYS5YyMiWrOpzTvqKjWIV7s/1mI=";
  };
  kube2pulumi = {
    pname = "kube2pulumi";
    version = "v0.0.11";
    src = fetchFromGitHub ({
      owner = "pulumi";
      repo = "kube2pulumi";
      rev = "v0.0.11";
      fetchSubmodules = false;
      sha256 = "sha256-CS6fSiSDJTQ6KKKZL7VRn8SRWjPqrGwLqcjLiCuW/U4=";
    });
    vendorSha256 = "sha256-Fk0YoS0mn1QANbFIA+jN+/bu0sim2wpAOcm/niYE1oc=";
  };
  kubectl-neat = {
    pname = "kubectl-neat";
    version = "v2.0.3";
    src = fetchurl {
      url = "https://github.com/itaysk/kubectl-neat/releases/download/v2.0.3/kubectl-neat_linux_amd64.tar.gz";
      sha256 = "sha256-sDYwCrM/og+f+fzYehvcMtyvcRC8KM3rh5qwfT2cljs=";
    };
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  revealjs = {
    pname = "revealjs";
    version = "4.1.2";
    src = fetchFromGitHub ({
      owner = "hakimel";
      repo = "reveal.js";
      rev = "4.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-8E0wG7xyAwyOp1zQWErY3eIipXii9LZm3iFKsznBgnw=";
    });
  };
  starship = {
    pname = "starship";
    version = "v1.9.1";
    src = fetchFromGitHub ({
      owner = "starship";
      repo = "starship";
      rev = "v1.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-IujaGyAGYlBb4efaRb13rsPSD2gWAg5UgG10iMp9iQE=";
    });
    cargoLock = {
      lockFile = ./starship-v1.9.1/Cargo.lock;
      outputHashes = {
      };
    };rustToolchainSha256 = "sha256-HhkjtODLw16O7DNPew9+vqOtbM6hcAmLH55XnZ0G6Fk=";
    rustToolchainChannel = "nightly";
    rustToolchainDate = "2022-07-01";
  };
}
